In [1]:
import numpy as np

In [11]:
#Ques 1
arr = np.array([10, 20, 30, 40, 50])
print("Original Array:", arr)
print("After adding 2:", arr + 2)
print("After multiplying by 3:", arr * 3)
print("After dividing by 2:", arr / 2)

Original Array: [10 20 30 40 50]
After adding 2: [12 22 32 42 52]
After multiplying by 3: [ 30  60  90 120 150]
After dividing by 2: [ 5. 10. 15. 20. 25.]


In [5]:
#Ques 2
arr = np.array([1, 2, 3, 6, 4, 5])
arr = np.array([1, 2, 3, 6, 4, 5])

print("Original Array:", arr)
print("Reversed Array:", arr[::-1])

Original Array: [1 2 3 6 4 5]
Reversed Array: [5 4 6 3 2 1]


In [6]:
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
values, counts = np.unique(x, return_counts=True)
most_frequent = values[np.argmax(counts)]
indices = np.where(x == most_frequent)[0]
print("Most frequent value:", most_frequent)
print("Frequency:", counts[np.argmax(counts)])
print("Indices:", indices)

Most frequent value: 1
Frequency: 5
Indices: [0 5 7 8 9]


In [7]:
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
values, counts = np.unique(y, return_counts=True)
most_frequent = values[np.argmax(counts)]
indices = np.where(y == most_frequent)[0]
print("Most frequent value:", most_frequent)
print("Frequency:", counts[np.argmax(counts)])
print("Indices:", indices)

Most frequent value: 1
Frequency: 3
Indices: [0 1 2]


In [8]:
#Ques 3
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
print("1st row, 2nd column:", arr[0, 1])
print("3rd row, 1st column:", arr[2, 0])

1st row, 2nd column: 20
3rd row, 1st column: 70


In [9]:
#Ques 5
import numpy as np
Arnav = np.linspace(10, 100, 25)
print("Array:")
print(Arnav)
print("Dimensions:", Arnav.ndim)
print("Shape:", Arnav.shape)
print("Total elements:", Arnav.size)
print("Data type:", Arnav.dtype)
print("Total bytes:", Arnav.nbytes)
transpose_Arnav = Arnav.reshape(1, 25)

print("Transpose using reshape():")
print(transpose_Arnav)


print("Transpose using T:")
print(Arnav.T)

Array:
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions: 1
Shape: (25,)
Total elements: 25
Data type: float64
Total bytes: 200
Transpose using reshape():
[[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
   47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
   85.    88.75  92.5   96.25 100.  ]]
Transpose using T:
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [10]:
#Ques 6
ucs420_Arnav = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 15, 20, 35]
])
print("Original Array:")
print(ucs420_Arnav)

print("Mean:", np.mean(ucs420_Arnav))

print("Median:", np.median(ucs420_Arnav))

print("Maximum:", np.max(ucs420_Arnav))

print("Minimum:", np.min(ucs420_Arnav))

print("Unique Elements:", np.unique(ucs420_Arnav))

reshaped_ucs420_Arnav = ucs420_Arnav.reshape(4, 3)

print("Reshaped Array (4 x 3):")
print(reshaped_ucs420_Arnav)

resized_ucs420_Arnav = np.resize(ucs420_Arnav, (2, 3))

print("Resized Array (2 x 3):")
print(resized_ucs420_Arnav)

Original Array:
[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]
Mean: 43.333333333333336
Median: 37.5
Maximum: 90
Minimum: 10
Unique Elements: [10 15 20 30 35 40 50 60 70 80 90]
Reshaped Array (4 x 3):
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized Array (2 x 3):
[[10 20 30]
 [40 50 60]]
