In [1]:
import numpy as np

In [38]:
#Ques 1
temperature = np.array([25, 28, 31, 35, 38, 27, 33, 40])
print("Incorrect tempratures:",temperature)
corrected_temperature = temperature + 2
print("Corrected temperatures:", corrected_temperature)

Incorrect tempratures: [25 28 31 35 38 27 33 40]
Corrected temperatures: [27 30 33 37 40 29 35 42]


In [5]:
fahrenheit = (9/5) * corrected_temperature + 32
print("Temperature in Fahrenheit:", fahrenheit)

Temperature in Fahrenheit: [ 80.6  86.   91.4  98.6 104.   84.2  95.  107.6]


In [6]:
readings_greater_32 = corrected_temperature[corrected_temperature > 32]
print("Readings greater than 32°C:", readings_greater_32)

Readings greater than 32°C: [33 37 40 35 42]


In [7]:
count = np.sum(corrected_temperature > 32)
print("Number of readings greater than 32°C:", count)

Number of readings greater than 32°C: 5


In [8]:
#Ques 2
steps = np.array([
    [5000, 6200, 7100],
    [8000, 7500, 9000],
    [4500, 5100, 4800],
    [9000, 8500, 9500]
])

In [10]:
total_steps = np.sum(steps)
print("Total steps:", total_steps)

Total steps: 84200


In [11]:
mean_steps = np.mean(steps)
print("Mean steps:", mean_steps)

Mean steps: 7016.666666666667


In [12]:
maximum = np.max(steps)
minimum = np.min(steps)
print("Maximum steps:", maximum)
print("Minimum steps:", minimum)

Maximum steps: 9500
Minimum steps: 4500


In [13]:
day_total = np.sum(steps, axis=0)
print("Total steps for each day:", day_total)

Total steps for each day: [26500 27300 30400]


In [14]:
user_total = np.sum(steps, axis=1)
print("Total steps for each user:", user_total)

Total steps for each user: [18300 24500 14400 27000]


In [15]:
position = np.unravel_index(np.argmax(steps), steps.shape)
print("Position of maximum steps:", position)
print("Maximum steps:", steps[position])

Position of maximum steps: (np.int64(3), np.int64(2))
Maximum steps: 9500


In [16]:
original = np.array([1, 2, 3, 4, 5, 6])
print("Original:", original)

Original: [1 2 3 4 5 6]


In [17]:
subset = original[1:5]
print("Subset:", subset)

Subset: [2 3 4 5]


In [18]:
subset[0] = 999
print("Original:", original)
print("Subset:", subset)

Original: [  1 999   3   4   5   6]
Subset: [999   3   4   5]


In [19]:
copied_array = original[1:5].copy()
copied_array[0] = 500
print("Original:", original)
print("Copied array:", copied_array)

Original: [  1 999   3   4   5   6]
Copied array: [500   3   4   5]


In [20]:
matrix = np.arange(1, 13).reshape(3, 4)
print(matrix)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [21]:
first_row = matrix[0]
print("First row:", first_row)

First row: [1 2 3 4]


In [22]:
flat_array = matrix.flatten()
print("Using flatten():", flat_array)

Using flatten(): [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [24]:
ravel_array = matrix.ravel()
print("Using ravel():", ravel_array)

Using ravel(): [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [25]:
ravel_array[0] = 100
print("Ravel array:", ravel_array)
print("Original matrix:")
print(matrix)

Ravel array: [100   2   3   4   5   6   7   8   9  10  11  12]
Original matrix:
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [26]:
matrix = np.arange(1, 13).reshape(3, 4)
flat_array = matrix.flatten()
flat_array[0] = 500
print("Flattened array:", flat_array)
print("Original matrix:")
print(matrix)

Flattened array: [500   2   3   4   5   6   7   8   9  10  11  12]
Original matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [27]:
print("Shape:", matrix.shape)
print("Number of dimensions:", matrix.ndim)
print("Size:", matrix.size)
print("Data type:", matrix.dtype)

Shape: (3, 4)
Number of dimensions: 2
Size: 12
Data type: int64


In [29]:
#Ques 4
y = np.array([40, 65, 30, 85])
X = np.array([
    [6, 70, 3],
    [5, 50, 6],
    [8, 80, 2],
    [4, 30, 8]
])

In [30]:
print("Shape of X:", X.shape)
print("Dimensions of X:", X.ndim)

Shape of X: (4, 3)
Dimensions of X: 2


In [31]:
print("Transpose of X:")
print(X.T)

Transpose of X:
[[ 6  5  8  4]
 [70 50 80 30]
 [ 3  6  2  8]]


In [32]:
XT_X = X.T @ X

print("X.T @ X:")
print(XT_X)

X.T @ X:
[[  141  1430    96]
 [ 1430 14700   910]
 [   96   910   113]]


In [33]:
inverse = np.linalg.inv(X.T @ X)

print("Inverse of X.T @ X:")
print(inverse)

Inverse of X.T @ X:
[[ 1.10521428 -0.09848746 -0.14581398]
 [-0.09848746  0.00891203  0.01190129]
 [-0.14581398  0.01190129  0.0368847 ]]


In [35]:
beta = np.linalg.inv(X.T @ X) @ X.T @ y
print("Beta coefficients:")
print(beta)

Beta coefficients:
[-0.15921454  0.14083853 10.06302242]


In [37]:
new_user = np.array([5, 40, 7])
new_user = np.array([5, 40, 7])

prediction = new_user @ beta

print("Predicted assistance score:", prediction)

Predicted assistance score: 75.27862544779018
